import mongoose, {Schema} from  "mongoose";
// import { decodedTextSpanIntersectsWith } from "typescript";

const UserSchema = new Schema ({

    username : {
        type : String,
        required : true,
        unique : true
    },
    password : {
        type : String,
        required : true
    }
})

const PositionSchema = new Schema({
    x :{
        type : Number,
        required : true
    },
    y : {
        type : Number,
        required : true
    }
},{
    _id : false
})

const EdgeSchema = new Schema({
    id : {
        type : String,
        required : true
    },
    source : {
        type : String,
        required : true
    },
    target : {
        type : String,
        required : true
    }
},{
    _id : false
})

const NodeDataSchema = new Schema({
    kind : {
        type : String,
        required : true,
        enum : ["TRIGGER", "ACTION"]
    },
        metadata : Schema.Types.Mixed,
},{
_id : false})

const WorkflowNodeSchema = new Schema({
    // frontend generates this id using Math.random().toString() and sends to backend while creating a node, backend uses this id to identify the node and update it with the correct ObjectId generated by MongoDB
    id :{
        type : String,
        required : true
    },
    positions : PositionSchema,
    credentials : Schema.Types.Mixed, 
    nodeId :{
        type : mongoose.Types.ObjectId,
        required : true,
        ref : "Nodes"
    },
    data : NodeDataSchema
},{
    _id : false
})

const WorkflowSchema = new Schema({
    userId : {
        type : mongoose.Types.ObjectId,
        required : true,
        ref : "Users"
    },
    nodes : [WorkflowNodeSchema],
    edges : [EdgeSchema]
})

const CredentialsTypeSchema = new Schema({
    title : {
        type : String,
        required : true
    },
    type : {
        type : String,
        required : true,
    },
    required :{
        type : Boolean,
        required : true
    }
})

const NodeSchema = new Schema({
    title:{
        type : String,
        required : true
    },
    description : {
        type : String,
        required : true
    },
    type : {
        type : String,
        enum : ["trigger", "action"],
        required : true
    },
    credentialsType : [CredentialsTypeSchema],
})

const ExecutionSchema = new Schema({
    workflowId : {
        type : mongoose.Types.ObjectId,
        required : true,
        ref : "Workflows"
    },
    status : {
        type : String,
        enum : ["PENDING", "COMPLETED", "FAILED"]
    },
    startTime : {
        type : Date,
        required : true,
        default : Date.now
    },
    endTime : {
        type : Date,
    }
})

// exporting collections
export const UserModel = mongoose.model("Users", UserSchema);
export const NodeModel = mongoose.model("Nodes", NodeSchema);
export const WorkflowModel = mongoose.model("Workflows", WorkflowSchema);
export const ExecutionModel = mongoose.model("Executions", ExecutionSchema);
